system.exec_command("xkbset -m")
system.exec_command("xmodmap -e \"keycode 54 = c\"")
system.exec_command("xmodmap -e \"keycode 39 = s\"")
system.exec_command("xmodmap -e \"keycode 38 = a\"")
dialog.info_dialog(message="stan_clicks off!")